version: '3.5'

services:
    nginx:
        image: nginx:stable-alpine
        container_name: gci-nginx
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker/default.conf:/etc/nginx/conf.d/default.conf

    php-fpm:
        build:
            context: ./
            dockerfile: docker/Dockerfile
        container_name: gci-php-fpm
        volumes:
            - ./:/var/www

    mysql:
        image: mysql:8
        container_name: gci-mysql
        restart: unless-stopped
        tty: true
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
